### PR TITLE
solr 7.4 xml response modify

### PR DESCRIPTION
**Pull request by search5**
In Solr 7.4, we modified to explicitly request an XML document, and modified the str element so that the string would go right into the arr element.

### CODE REVIEW

**Comment by edsu** [comment]
Thanks for this. If you would like me to transfer this repository to you please let me know. I no longer actively use the code myself, but I suspect there are those that do.

**Comment by search5** [comment]
@edsu I am willing to transfer the solrpy repository. My github account is search5. I forgot what I forked. Please send the repository at any time.

And I use solrpy relatively positively. And if you send us the original source code of the pickle file used in tests.py, we can think about modifying it for Python 3 version again.

Thank you for the patch.

**Comment by edsu** [comment]
Great! It would be good to have someone actively tending to the code.  I saw that there was a solrpy3 on pypi, so it would be good to upgrade solrpy to hopefully avoid some confusion/duplicate work. I'll transfer the repository now.

**Comment by search5** [comment]
@edsu The solrpy repository has not been transferred, what happens? I was waiting for you to send it right away. Also, I would like to add search5 as a maintainer to pypi's solrpy page with repository transfer

**Comment by edsu** [comment]
Sorry for the delay. I've added you as an owner on PyPI. Please remove or rename your existing solrpy repository, the transfer can't proceed since you have it already.

**Comment by search5** [comment]
@edsu Thanks. project rename success. please solrpy respository transfer request.

**Comment by edsu** [comment]
Should I apply your open PRs and then you can delete your repo while keeping a local copy? Then I will transfer?

**Comment by search5** [comment]
You do not need to apply OpenPR. I will do that application. I deleted the
project I forked. I would like to transfer the repository.
---
학교 : 한국방송통신대학교 대학원 정보과학과 / 석사 재학
Callable: 010-2758-7508 / search5@gmail.com


2018년 9월 25일 (화) 오전 2:27, Ed Summers <notifications@github.com>님이 작성:

**Pull request merged**
